version: '3'

networks:
  ecovacs_stack:
    internal: true
services:
  generate-cert:
    build:
      context: ./generateCert
      dockerfile: Dockerfile
    networks:
      default:
    volumes:
      - './generateCert/config:/config'
    command: ash -c './generate-cert.sh'
    # user: 1000:1000
    stdin_open: true

  request-listener:
    build:
      context: ./requestListener
      dockerfile: Dockerfile
    networks:
      ecovacs_stack:
    volumes:
      - ./requestListener:/opt/app
    user: 1000:1000
    command: bash -c 'yarn install && yarn run dev'
    stdin_open: true

  nginx:
    depends_on:
      - request-listener
    image: nginx:alpine
    ports:
      - 8883:8883
      - 443:443
    networks:
      default:
      ecovacs_stack:
    # network_mode: host
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/:/etc/nginx:ro

  mqtt:
    depends_on:
      - nginx
    build:
      context: ./mqtt
      dockerfile: Dockerfile
    environment:
      NODE_OPTIONS: --max-old-space-size=8192

    networks:
      ecovacs_stack:
      default:
    volumes:
      - ./mqtt:/opt/app
    command: bash -c 'yarn install && yarn run dev'
    stdin_open: true
