version: '3'

networks:
  ecovacs_stack:
    internal: true
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      ecovacs_stack:
      default:
    volumes:
      - ./backend:/opt/app
    user: 1000:1000
    environment:
      - BASE_URL=https://localhost
      - BASE_URL_01=https//ecovacs.com
    command: bash -c './generate_certs.sh && yarn install && yarn run dev'

    stdin_open: true

  nginx:
    depends_on:
      - backend
    image: nginx:alpine
    ports:
      - 8883:8883
      - 443:443
      - 3000:3000
      - 80:80
    networks:
      default:
      ecovacs_stack:
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/:/etc/nginx:ro
  frontend:
    depends_on:
      - nginx
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - WDS_SOCKET_PORT=0
    networks:
      default:
    volumes:
      - ./frontend:/opt/app
    ports:
      - 4200:3000
    command: bash -c 'yarn install && yarn start'
    stdin_open: true
