version: '3'
services:
  broker:
    build:
      context: ./broker
      dockerfile: Dockerfile
    network_mode: 'host'
    volumes:
      - './broker/config:/mosquitto/config'
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 8883:8883
      - 443:8883
    stdin_open: true
  backend:
    depends_on:
      - broker
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - './backend:/opt/app'
    ports:
      - 8080:8080
    command: bash -c 'yarn install && yarn run dev'
    stdin_open: true
