version: '3'

networks:
  ecovacs_stack:
    internal: true
services:
  generate-cert:
    build:
      context: ./generateCert
      dockerfile: Dockerfile
    networks:
      default:
    volumes:
      - './generateCert/config:/config'
    command: ash -c './generate-cert.sh'
    # user: 1000:1000
    stdin_open: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      ecovacs_stack:
      default:
    volumes:
      - ./backend:/opt/app
    user: 1000:1000
    # environment:
    #   - NODE_OPTIONS="--max-old-space-size=8192"
    command: bash -c 'yarn install && yarn run dev'
    stdin_open: true

  nginx:
    depends_on:
      - backend
    image: nginx:alpine
    ports:
      - 8883:8883
      - 443:443
      - 3000:3000
    networks:
      default:
      ecovacs_stack:
    # network_mode: host
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/:/etc/nginx:ro
  frontend:
    depends_on:
      - nginx
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      ecovacs_stack:
      default:
    volumes:
      - ./frontend:/opt/app
    ports:
      - 4200:3000
    command: bash -c 'yarn install && yarn start'
    stdin_open: true
